baseURL = "https://netibex.netlify.com"
languageCode = "en-us"
Title= "Netibex*Blog"
paginate = 10
#DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - Netibex"
canonifyurls = true
theme="nbcasper"


[params]
  description = "a blog about tech and other things"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  #cover = "images/cover.jpg"
  author = "Christoph*"
  authorlocation = " ... above clouds"
  authorwebsite = "https://netibex.netlify.com"
  authorbio= "Always strive to learn..."
  logowhite = "images/logo-white.png"
  #googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "netibex"
  #twitterName = "netibex"
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  # email = ""
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"
  #pygmentsUseClassic=true

  [params.social]
    twitter = "your_twitter"

	
[[menu.main]]
  name = "Home"
  weight = -100
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "#Tech"
  weight = -110
  identifier = "tech"
  url = "/tags/tech/"

[[menu.main]]
  name = "#AllThingsLife"
  weight = -120
  identifier = "life"
  url = "/tags/life/"

[[menu.main]]
  name = "About"
  weight = -200
  identifier = "about"
  url = "/about"
