name = "nbcasper"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Netibex theme ported from Casper"
homepage = "http://vjeantet.fr/"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.25

[author]
  name = "Christoph"
  homepage = "https://netibex.netlify.com"

[original]
  name = "Casper"
  homepage = "https://github.com/vjeantet/hugo-theme-casper"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
  
